export type Platform = "Webflow" | "Shopify" | "WordPress" | "Wix";

export type Category =
  | "Fashion & Apparel"
  | "Beauty & Cosmetics"
  | "Mobile & Electronics"
  | "Automotive"
  | "Dental & Healthcare"
  | "Home & Trade Services"
  | "Corporate & Consulting"
  | "eCommerce & Retail"
  | "Lighting & Interiors"
  | "Marketing & Brand";

export type Project = {
  slug: string;
  name: string;
  platform: Platform;
  category: Category;
  url: string;
  description: string;
  year: string;
  tags: string[];
};

// Live screenshots via WordPress.com mShots — free, cached, no watermark.
export function screenshotFor(url: string, w = 1280, h = 900) {
  const clean = encodeURIComponent(url.replace(/^https?:\/\//, "").replace(/\/$/, ""));
  return `https://s.wordpress.com/mshots/v1/https://${clean}?w=${w}&h=${h}`;
}

export const projects: Project[] = [
  // ── Fashion & Apparel ─────────────────────────────────────────────
  {
    slug: "house-of-faraz",
    name: "House of Faraz",
    platform: "Shopify",
    category: "Fashion & Apparel",
    url: "https://houseoffaraz.com/",
    description:
      "Luxury menswear Shopify store with editorial collection pages, refined typography and a smooth checkout.",
    year: "2025",
    tags: ["eCommerce", "Menswear"],
  },
  {
    slug: "house-of-siyaab",
    name: "House of Siyaab",
    platform: "Shopify",
    category: "Fashion & Apparel",
    url: "https://houseofsiyaab.com/",
    description:
      "Contemporary womenswear Shopify build — clean PDPs, size-guide integration and frictionless checkout.",
    year: "2025",
    tags: ["eCommerce", "Womenswear"],
  },
  {
    slug: "the-honest-crown",
    name: "The Honest Crown",
    platform: "Shopify",
    category: "Fashion & Apparel",
    url: "https://thehonestcrown.com/",
    description: "Modern apparel brand storefront with a bold identity and editorial product storytelling.",
    year: "2025",
    tags: ["eCommerce", "Apparel"],
  },
  {
    slug: "verbero",
    name: "Verbero",
    platform: "Shopify",
    category: "Fashion & Apparel",
    url: "https://www.verbero.com/",
    description: "Sports apparel & equipment eCommerce — configurable products, deep filtering and global shipping.",
    year: "2024",
    tags: ["eCommerce", "Sports"],
  },
  {
    slug: "xeroloops",
    name: "Xeroloops",
    platform: "Shopify",
    category: "Fashion & Apparel",
    url: "https://xeroloops.com/",
    description: "Direct-to-consumer Shopify brand build with a fast, editorial storefront.",
    year: "2024",
    tags: ["eCommerce", "D2C"],
  },

  // ── Beauty & Cosmetics ────────────────────────────────────────────
  {
    slug: "adorable-cosmetics",
    name: "Adorable Cosmetics",
    platform: "Shopify",
    category: "Beauty & Cosmetics",
    url: "https://adorablecosmeticspk.com/",
    description: "Cosmetics Shopify storefront with vibrant product pages, bundles and a conversion-focused PDP.",
    year: "2025",
    tags: ["eCommerce", "Beauty"],
  },
  {
    slug: "iris-premium",
    name: "Iris Premium",
    platform: "Shopify",
    category: "Beauty & Cosmetics",
    url: "https://irisspremium.com/",
    description: "Premium lifestyle & beauty brand — polished Shopify build with rich collection pages.",
    year: "2025",
    tags: ["eCommerce", "Premium"],
  },
  {
    slug: "londontown",
    name: "London Town USA",
    platform: "Shopify",
    category: "Beauty & Cosmetics",
    url: "https://www.londontownusa.com/",
    description: "Beauty & nail lacquer eCommerce — custom theme, subscription flow and CRO-focused PDP.",
    year: "2024",
    tags: ["eCommerce", "Beauty"],
  },
  {
    slug: "kamana",
    name: "Kamana",
    platform: "Shopify",
    category: "Beauty & Cosmetics",
    url: "https://kamana.co/",
    description: "Modern lifestyle Shopify build with editorial product storytelling.",
    year: "2024",
    tags: ["eCommerce", "Lifestyle"],
  },

  // ── Mobile & Electronics ──────────────────────────────────────────
  {
    slug: "phonebuyer",
    name: "Phone Buyer",
    platform: "WordPress",
    category: "Mobile & Electronics",
    url: "https://phonebuyer.ae/",
    description: "Device trade-in & resale platform — instant-quote flow and a clean UAE-focused storefront.",
    year: "2025",
    tags: ["Mobile", "Trade-in"],
  },
  {
    slug: "phoneexits",
    name: "Phone Exits",
    platform: "WordPress",
    category: "Mobile & Electronics",
    url: "https://phoneexits.com/",
    description: "Buy & sell mobile marketplace — device catalog, valuation forms and lead capture.",
    year: "2025",
    tags: ["Mobile", "Marketplace"],
  },
  {
    slug: "quickcellphone",
    name: "Quick Cell Phone",
    platform: "WordPress",
    category: "Mobile & Electronics",
    url: "https://quickcellphone.com/",
    description: "Phone-repair storefront — device-specific service pages and fast local booking.",
    year: "2024",
    tags: ["Repair", "Local"],
  },
  {
    slug: "multypower",
    name: "Multy Power",
    platform: "WordPress",
    category: "Mobile & Electronics",
    url: "https://multypower.ae/",
    description: "Electronics & power-solutions brand site with a modern product-led layout.",
    year: "2025",
    tags: ["Electronics", "Brand"],
  },
  {
    slug: "seus-lighting",
    name: "Seus Lighting",
    platform: "Shopify",
    category: "Lighting & Interiors",
    url: "https://www.seuslighting.com/",
    description: "Lighting eCommerce store — large catalog, faceted filtering and a premium PDP experience.",
    year: "2025",
    tags: ["eCommerce", "Lighting"],
  },
  {
    slug: "lather",
    name: "Lather Hotel",
    platform: "Shopify",
    category: "Lighting & Interiors",
    url: "https://www.latherhotel.com/",
    description: "Hospitality-inspired Shopify store — premium PDP and immersive collection pages.",
    year: "2024",
    tags: ["eCommerce", "Hospitality"],
  },
  {
    slug: "vitkonwood",
    name: "Vitkon Wood",
    platform: "Shopify",
    category: "Lighting & Interiors",
    url: "https://vitkonwood.de/",
    description: "European furniture Shopify store with localized checkout and configurable products.",
    year: "2024",
    tags: ["eCommerce", "Furniture"],
  },
  {
    slug: "property-spa",
    name: "Property Spa",
    platform: "WordPress",
    category: "Lighting & Interiors",
    url: "https://propertyspa.com/",
    description: "Home & property services brand — clean WordPress build with service pages and inquiry flow.",
    year: "2024",
    tags: ["Home", "Services"],
  },

  // ── Automotive ────────────────────────────────────────────────────
  {
    slug: "original-emev-parts",
    name: "Original EMEV Parts",
    platform: "Shopify",
    category: "Automotive",
    url: "https://originalemevparts.com/",
    description: "EV parts eCommerce — structured catalog, fitment info and a streamlined Shopify checkout.",
    year: "2025",
    tags: ["eCommerce", "EV Parts"],
  },
  {
    slug: "grand-city-garage",
    name: "Grand City Garage",
    platform: "WordPress",
    category: "Automotive",
    url: "https://grandcitygarage.com/",
    description: "Auto repair & service center — WordPress site with booking, services and location SEO.",
    year: "2025",
    tags: ["Automotive", "Booking"],
  },
  {
    slug: "amrik-workshop",
    name: "Amrik International Workshop",
    platform: "WordPress",
    category: "Automotive",
    url: "https://amrikinternationalworkshop.com/",
    description: "Automotive workshop brand site with service catalogue and quote requests.",
    year: "2025",
    tags: ["Automotive", "Services"],
  },
  {
    slug: "flyride-frankfurt",
    name: "Flyride Frankfurt",
    platform: "WordPress",
    category: "Automotive",
    url: "https://flyridefrankfurt.de/",
    description: "Mobility & ride service in Frankfurt — localized WordPress build with booking flow.",
    year: "2025",
    tags: ["Mobility", "Booking"],
  },
  {
    slug: "haulingops",
    name: "Hauling Ops",
    platform: "WordPress",
    category: "Automotive",
    url: "https://www.haulingops.com/",
    description: "Hauling & logistics company site with service-area pages and a clear quote funnel.",
    year: "2024",
    tags: ["Logistics", "Lead-gen"],
  },
  {
    slug: "octacargo",
    name: "Octa Cargo",
    platform: "WordPress",
    category: "Automotive",
    url: "https://octacargo.ca/",
    description: "Freight & cargo services site — WordPress build with tracking and inquiry sections.",
    year: "2024",
    tags: ["Logistics", "Services"],
  },
  {
    slug: "shiplayerusa",
    name: "Shiplayer USA",
    platform: "WordPress",
    category: "Automotive",
    url: "https://shiplayerusa.com/",
    description: "Shipping & fulfilment brand site with clear service tiers and lead capture.",
    year: "2024",
    tags: ["Logistics", "Lead-gen"],
  },

  // ── Dental & Healthcare ───────────────────────────────────────────
  {
    slug: "simply-smiles-arrowhead",
    name: "Simply Smiles Arrowhead",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://simplysmilesarrowhead.com/",
    description: "Dental practice site — appointment booking, service pages and local-SEO structure.",
    year: "2025",
    tags: ["Dental", "Booking"],
  },
  {
    slug: "simply-smiles-dentist",
    name: "Simply Smiles Dentist",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://simplysmilesdentist.com/",
    description: "Family dentistry WordPress build with clean service pages and online scheduling.",
    year: "2025",
    tags: ["Dental", "Booking"],
  },
  {
    slug: "clarksville-smiles",
    name: "Clarksville Smiles",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://clarksvillesmilestn.com/",
    description: "Local dental brand — WordPress site with treatment pages and a strong local presence.",
    year: "2025",
    tags: ["Dental", "Local SEO"],
  },
  {
    slug: "pearly-smile-studio",
    name: "Pearly Smile Dental Studio",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://pearlysmiledentalstudio.com/",
    description: "Modern dental studio site with a warm palette, service tree and booking CTAs.",
    year: "2024",
    tags: ["Dental", "Booking"],
  },
  {
    slug: "care-for-you-dental",
    name: "Care For You Dental",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://careforyoudental.com/",
    description: "Patient-first dental practice WordPress site with clear services and contact flow.",
    year: "2024",
    tags: ["Dental", "Services"],
  },
  {
    slug: "pearl-dental-group",
    name: "Pearl Dental Group",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://www.pearldentalgroup.com/",
    description: "Multi-provider dental group site with team pages, services and appointment booking.",
    year: "2024",
    tags: ["Dental", "Group"],
  },
  {
    slug: "dental-implants-tucson",
    name: "Dental Implants Tucson",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://dentalimplantstucsoncenter.com/",
    description: "Implant-focused dental landing site with procedure pages and consultation funnels.",
    year: "2024",
    tags: ["Dental", "Lead-gen"],
  },
  {
    slug: "dental-seo-services",
    name: "Dental SEO Services",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://dentalseoservicescompany.com/",
    description: "Marketing agency for dental practices — WordPress site with case studies and SEO content.",
    year: "2024",
    tags: ["Marketing", "SEO"],
  },
  {
    slug: "home-health-care-seattle",
    name: "Home Health Care Seattle",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://homehealthcareseattle.com/",
    description: "In-home care provider site — service pages, trust signals and inquiry forms.",
    year: "2024",
    tags: ["Healthcare", "Lead-gen"],
  },
  {
    slug: "mediguard",
    name: "MediGuard",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://getmediguard.com/",
    description: "Healthcare product site — custom theme, lead-gen funnels and HIPAA-aware forms.",
    year: "2024",
    tags: ["Healthcare", "Lead-gen"],
  },
  {
    slug: "positive-pathways-aba",
    name: "Positive Pathways ABA",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://positivepathwaysaba.com/",
    description: "ABA therapy provider site — approachable design, service pages and family resources.",
    year: "2025",
    tags: ["Therapy", "Care"],
  },
  {
    slug: "new-dawn-aba",
    name: "New Dawn ABA",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://newdawnaba.com/",
    description: "ABA care brand — WordPress build with warm visuals, services and intake forms.",
    year: "2025",
    tags: ["Therapy", "Care"],
  },
  {
    slug: "westpoint-optical",
    name: "Westpoint Optical",
    platform: "WordPress",
    category: "Dental & Healthcare",
    url: "https://westpointoptical.ca/",
    description: "Optometry clinic site — eyewear showcase, exam booking and clear service pages.",
    year: "2024",
    tags: ["Optical", "Booking"],
  },

  // ── Home & Trade Services ─────────────────────────────────────────
  {
    slug: "porterfield-stump-tree",
    name: "Porterfield Stump & Tree",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://porterfieldstumpandtree.com/",
    description: "Tree & stump removal service — WordPress site with gallery, service-area pages and quotes.",
    year: "2025",
    tags: ["Tree Care", "Lead-gen"],
  },
  {
    slug: "bg-tree-care",
    name: "BG Tree Care",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://bgtreecare.com/",
    description: "Tree-care specialists — WordPress build with service pages and a clear estimate flow.",
    year: "2025",
    tags: ["Tree Care", "Local"],
  },
  {
    slug: "affordable-tree-landscape",
    name: "Affordable Tree & Landscape",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://affordabletreelandscape.com/",
    description: "Landscaping & tree services company site with gallery and quote requests.",
    year: "2025",
    tags: ["Landscaping", "Lead-gen"],
  },
  {
    slug: "arbormax-pa",
    name: "ArborMax PA",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://arbormaxpa.com/",
    description: "Arborist & tree service in Pennsylvania — WordPress site with local-SEO structure.",
    year: "2025",
    tags: ["Tree Care", "Local SEO"],
  },
  {
    slug: "alabama-comfort-controls",
    name: "Alabama Comfort Controls",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://alabamacomfortcontrols.com/",
    description: "HVAC company site — service pages, financing info and a strong booking CTA.",
    year: "2025",
    tags: ["HVAC", "Lead-gen"],
  },
  {
    slug: "quality-paint-services",
    name: "Quality Paint Services",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://qualitypaintservicestn.com/",
    description: "Painting contractor site with project gallery, service pages and estimate form.",
    year: "2024",
    tags: ["Painting", "Gallery"],
  },
  {
    slug: "coastal-softwash",
    name: "Coastal Softwash Solutions",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://coastalsoftwashsolutions.com/",
    description: "Exterior cleaning & softwash company — WordPress site with before/after gallery and quotes.",
    year: "2024",
    tags: ["Cleaning", "Gallery"],
  },
  {
    slug: "cleaning-now-nc",
    name: "Cleaning Now NC",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://cleaningnownc.com/",
    description: "Residential & commercial cleaning brand with clear service pages and inquiry flow.",
    year: "2024",
    tags: ["Cleaning", "Lead-gen"],
  },
  {
    slug: "arya-fire-protection",
    name: "Arya Fire Protection",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://aryafireprotection.com/",
    description: "Fire-protection services site — compliance-focused content and service catalogue.",
    year: "2024",
    tags: ["Safety", "Services"],
  },
  {
    slug: "rocket-locksmith",
    name: "Rocket Locksmith",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://www.rocket-locksmith.com/",
    description: "24/7 locksmith service — WordPress site with emergency CTAs and service-area SEO.",
    year: "2024",
    tags: ["Local Services", "SEO"],
  },
  {
    slug: "jarzys",
    name: "Jarzy's Appliances",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://jarzysappliances.co.uk/",
    description: "Appliance repair service — WordPress build with quote form and service-area pages.",
    year: "2025",
    tags: ["Repair", "Lead-gen"],
  },
  {
    slug: "allprocleans",
    name: "AllPro Cleans",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://allprocleans.co.uk/",
    description: "Commercial cleaning company site — clear service pages and inquiry flow.",
    year: "2025",
    tags: ["Cleaning", "Lead-gen"],
  },
  {
    slug: "chefcool",
    name: "Chef Cool",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://chefcool.co.uk/",
    description: "Commercial refrigeration engineers — WordPress marketing site with booking form.",
    year: "2025",
    tags: ["Refrigeration", "Booking"],
  },
  {
    slug: "clenova",
    name: "Clenova",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://clenova.co.uk/",
    description: "Cleaning-services brand — modern WordPress build with service pages and quote form.",
    year: "2025",
    tags: ["Cleaning", "Lead-gen"],
  },
  {
    slug: "cloud9-glazing",
    name: "Cloud 9 Glazing",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://cloud9glazing.com/",
    description: "Window & glazing specialists — WordPress site with gallery and estimate form.",
    year: "2025",
    tags: ["Glazing", "Gallery"],
  },
  {
    slug: "fisher-scaffolding",
    name: "Fisher Scaffolding",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://www.fisherscaffolding.co.uk/",
    description: "Scaffolding contractor — WordPress marketing site with project gallery and quote flow.",
    year: "2025",
    tags: ["Construction", "Lead-gen"],
  },
  {
    slug: "pest-control-bromley",
    name: "Pest Control Bromley",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://pestcontrolbromley.co.uk/",
    description: "Local pest-control company — WordPress site with pest-specific service pages and SEO.",
    year: "2025",
    tags: ["Pest Control", "SEO"],
  },
  {
    slug: "window-repairs-lichfield",
    name: "Window Repairs Lichfield",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://windowrepairslichfield.co.uk/",
    description: "Local window-repair specialist — WordPress build with clear service tree and CTAs.",
    year: "2025",
    tags: ["Repair", "Lead-gen"],
  },
  {
    slug: "pest-control-proofing",
    name: "Pest Control & Proofing",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://pestcontrolandproofing.co.uk/",
    description: "Pest-control and proofing services — WordPress site with treatment-specific pages.",
    year: "2025",
    tags: ["Pest Control", "SEO"],
  },
  {
    slug: "essex-window-care",
    name: "Essex Window Care",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://essexwindowcare.co.uk/",
    description: "Window installation & repair company — WordPress site with gallery and quotes.",
    year: "2025",
    tags: ["Glazing", "Gallery"],
  },
  {
    slug: "ashmore-plastering",
    name: "Ashmore Plastering",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://ashmoreplastering.com/",
    description: "Plastering contractor — WordPress marketing site with project gallery and lead form.",
    year: "2025",
    tags: ["Construction", "Gallery"],
  },
  {
    slug: "streetly-window-repairs",
    name: "Streetly Window Repairs",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://streetlywindowrepairs.com/",
    description: "Window repair specialist — WordPress site optimised for local search and calls.",
    year: "2025",
    tags: ["Repair", "SEO"],
  },
  {
    slug: "0121-repairs",
    name: "0121 Repairs",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://0121repairs.co.uk/",
    description: "Birmingham appliance-repair brand — WordPress build with service-area SEO structure.",
    year: "2025",
    tags: ["Repair", "SEO"],
  },
  {
    slug: "st-joseph-boat-rentals",
    name: "St Joseph Boat Rentals",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://www.stjosephboatrentals.com/",
    description: "Boat rental business — WordPress site with fleet showcase and online booking inquiry.",
    year: "2025",
    tags: ["Rentals", "Booking"],
  },
  {
    slug: "mini-travel-executive",
    name: "Mini Travel Executive",
    platform: "WordPress",
    category: "Home & Trade Services",
    url: "https://minitravelexecutive.co.uk/",
    description: "Executive travel service — WordPress site with fleet showcase and booking inquiry.",
    year: "2025",
    tags: ["Travel", "Booking"],
  },

  // ── Corporate & Consulting ────────────────────────────────────────
  {
    slug: "codevium-digital",
    name: "Codevium Digital",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://www.codeviumdigital.com/",
    description: "Digital agency brand site — modern layout, service pages and case-study sections.",
    year: "2024",
    tags: ["Agency", "Brand"],
  },
  {
    slug: "abs-developers",
    name: "ABS Developers",
    platform: "Shopify",
    category: "Corporate & Consulting",
    url: "https://abs-developers.com/",
    description: "Real-estate & development brand storefront with project listings and inquiry flow.",
    year: "2025",
    tags: ["Real Estate", "Brand"],
  },
  {
    slug: "american-first-accounting",
    name: "American First Accounting",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://americanfirstaccounting.com/",
    description: "Accounting firm site — trust-first design, service pages and consultation booking.",
    year: "2024",
    tags: ["Accounting", "Services"],
  },
  {
    slug: "tax-accountant-boca-raton",
    name: "Tax Accountant Boca Raton",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://taxaccountantservicesbocaraton.com/",
    description: "Local tax & accounting services site with service pages and lead capture.",
    year: "2024",
    tags: ["Accounting", "Local SEO"],
  },
  {
    slug: "fortis-aml-consulting",
    name: "Fortis AML Consulting",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://fortisamlconsulting.com/",
    description: "Compliance & AML consultancy — clean corporate WordPress build with service pages.",
    year: "2024",
    tags: ["Consulting", "Compliance"],
  },
  {
    slug: "outbounds",
    name: "Outbound TS",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://outboundts.com/",
    description: "B2B sales & outbound agency site with service tiers and conversion-led layout.",
    year: "2024",
    tags: ["B2B", "Agency"],
  },
  {
    slug: "residency-malta",
    name: "Residency by Investment Malta",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://residencybyinvestmentinmalta.com/",
    description: "Immigration & residency advisory site — informational content and consultation funnels.",
    year: "2024",
    tags: ["Advisory", "Lead-gen"],
  },
  {
    slug: "product-catalog-software",
    name: "Product Catalog Management",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "http://productcatalogmanagementsoftware.com/",
    description: "SaaS marketing site for a catalog-management product with feature and pricing sections.",
    year: "2024",
    tags: ["SaaS", "Marketing"],
  },
  {
    slug: "techsmart-fs",
    name: "TechSmart FS",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://techsmartfs.co.uk/",
    description: "Facilities-services company — WordPress build with service catalogue and inquiry flow.",
    year: "2025",
    tags: ["B2B", "Facilities"],
  },
  {
    slug: "michael-coleman",
    name: "Michael Coleman",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://michaelcoleman.com/",
    description: "Personal brand & consulting site with structured content, blog and booking integration.",
    year: "2024",
    tags: ["Personal Brand", "Blog"],
  },
  {
    slug: "st-elder",
    name: "ST Elder",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://st-elder.com/",
    description: "Services company site with a bespoke design and modular content sections.",
    year: "2024",
    tags: ["Services", "Custom Theme"],
  },
  {
    slug: "angels-among-us",
    name: "Angels Among Us Foundation",
    platform: "Wix",
    category: "Corporate & Consulting",
    url: "https://www.angelsamongusfoundation.org/",
    description: "Non-profit foundation site — Wix build with donations, programs and story-led content.",
    year: "2025",
    tags: ["Non-profit", "Donations"],
  },
  {
    slug: "gmccx",
    name: "GMCCX",
    platform: "Wix",
    category: "Corporate & Consulting",
    url: "https://www.gmccx.com/",
    description: "Corporate services brand — Wix site with structured service pages and contact flow.",
    year: "2025",
    tags: ["Corporate", "Services"],
  },
  {
    slug: "thompson-jiujitsu",
    name: "Thompson Jiu-Jitsu",
    platform: "WordPress",
    category: "Corporate & Consulting",
    url: "https://thompsonjiujitsu.com/",
    description: "Martial-arts academy site — class schedules, membership info and trial-signup CTAs.",
    year: "2025",
    tags: ["Fitness", "Booking"],
  },

  // ── Marketing & Brand (Webflow flagships) ─────────────────────────
  {
    slug: "swankey",
    name: "Swankey",
    platform: "Webflow",
    category: "Marketing & Brand",
    url: "https://www.swankey.com/",
    description:
      "Product studio site rebuilt in Webflow with fluid interactions, custom cursor states and a strict typographic grid.",
    year: "2025",
    tags: ["Studio", "Interactions"],
  },
  {
    slug: "synrg",
    name: "Synrg",
    platform: "Webflow",
    category: "Marketing & Brand",
    url: "https://www.synrg.ai/",
    description: "AI product marketing site — motion-heavy hero, dark-mode aesthetic and CMS-driven docs.",
    year: "2024",
    tags: ["AI", "Product"],
  },
  {
    slug: "knownwell",
    name: "Known Well",
    platform: "Webflow",
    category: "Marketing & Brand",
    url: "https://www.knownwell.co/",
    description: "Health & wellness brand — warm palette, editorial layouts and a CMS blog.",
    year: "2024",
    tags: ["Wellness", "CMS"],
  },
  {
    slug: "baycrest",
    name: "Baycrest Consulting",
    platform: "Webflow",
    category: "Marketing & Brand",
    url: "https://baycrest-consulting.webflow.io/",
    description: "Consulting brand site — refined typography and subtle scroll storytelling.",
    year: "2024",
    tags: ["Consulting", "Brand"],
  },
  {
    slug: "x-analytics",
    name: "X Analytics",
    platform: "Webflow",
    category: "Marketing & Brand",
    url: "https://www.x-analytics.com/",
    description: "Data & analytics platform marketing site with modular sections and CMS docs.",
    year: "2023",
    tags: ["SaaS", "Analytics"],
  },
  {
    slug: "3types",
    name: "3 Types",
    platform: "Webflow",
    category: "Marketing & Brand",
    url: "https://www.3types.com/",
    description: "Editorial-style brand site with rich transitions and content-first storytelling.",
    year: "2024",
    tags: ["Brand", "Editorial"],
  },
  {
    slug: "chic-design",
    name: "Chic Design",
    platform: "Webflow",
    category: "Marketing & Brand",
    url: "https://www.chicdnr.com/",
    description: "Interior design studio portfolio — big imagery, quiet type, generous white space.",
    year: "2023",
    tags: ["Portfolio", "Design"],
  },
];

export const categories: Category[] = [
  "Fashion & Apparel",
  "Beauty & Cosmetics",
  "Mobile & Electronics",
  "Automotive",
  "Dental & Healthcare",
  "Lighting & Interiors",
  "Home & Trade Services",
  "Corporate & Consulting",
  "Marketing & Brand",
];

export const platformCounts = () => {
  const map: Record<string, number> = {};
  for (const p of projects) map[p.platform] = (map[p.platform] ?? 0) + 1;
  return map;
};

export const featured = [
  projects.find((p) => p.slug === "house-of-faraz")!,
  projects.find((p) => p.slug === "swankey")!,
  projects.find((p) => p.slug === "seus-lighting")!,
  projects.find((p) => p.slug === "original-emev-parts")!,
  projects.find((p) => p.slug === "synrg")!,
  projects.find((p) => p.slug === "adorable-cosmetics")!,
].filter(Boolean);
